language = "untyped λ-calculus"
fragment = "pattern"

[[problems]]
constraints = [
    "∀ f, x . X[f, x] = f Y[x]",
    "∀ x . Y[x] = x x"
]

[[problems.solutions]]
name = "most general"
substitutions = [
    "Y[x] ↦ x x",
    "X[f, x] ↦ f (x x)",
]

[[problems.solutions]]
name = "with redundant substitution"
substitutions = [
    "Y[x] ↦ x x",
    "X[f, x] ↦ f (x x)",
    "M[x, y] ↦ y x"
]
