language = "typed λ-calculus"
fragment = "pattern"

[[problems]]
metavars = [
    "X: [t -> t, t] t",
    "Y: [t] t",
    "M: [t, t -> t] t"
]
constraints = [
    "∀ f: t -> t, x: t. X[f, x] = f Y[x]",
    "∀ x: t. Y[x] = x"
]

[[problems.solutions]]
name = "most general"
metavars = []
substitutions = [
    "Y[a] ↦ a",
    "X[b, c] ↦ b c",
]

[[problems.solutions]]
name = "with redundant substitution"
metavars = []
substitutions = [
    "Y[x] ↦ x",
    "X[f, x] ↦ f x",
    "M[x, y] ↦ y x"
]

# [[problems]]
# metavars = [
#     "X: [t -> t, t, t] t",
#     "Y: [t, t, t] t",
# ]
# constraints = [
#     "∀ a: t -> t, b: t, c: t. X[a, b, a c] = Y[b, c, a b]",
# ]

# [[problems.solutions]]
# metavars = [
#     "M: [t -> t, t, t] t",
# ]
# name = "most general solution with new metavariable"
# substitutions = [
#     "X[x, y, z] ↦ M[y, x y]", # "X[x, y, z] ↦ y",
#     "Y[x, y, z] ↦ M[x, z]",   # "X[x, y, z] ↦ x y",
# ]
