language = "typed λ-calculus"
fragment = "pattern"

[[problems]]
metavars = [
    "X: [t -> t, t] t",
    "Y: [t] t",
    "M: [t, t -> t] t"
]
constraints = [
    "∀ f: t -> t, x: t. X[f, x] = f Y[x]",
    "∀ x: t. Y[x] = x"
]

[[problems.solutions]]
name = "most general"
substitutions = [
    "Y[a] ↦ a",
    "X[b, c] ↦ b c",
]

[[problems.solutions]]
name = "with redundant substitution"
substitutions = [
    "Y[x] ↦ x",
    "X[f, x] ↦ f x",
    "M[x, y] ↦ y x"
]
