language = "untyped λ-calculus"
fragment = "pattern"

[[problems]]
constraints = [
    "∀ f: magic -> t, x: magic. X[f, x] = f Y[x]",
    "∀ x: magic. Y[x] = x x"
]

[[problems.solutions]]
name = "most general"
substitutions = [
    "Y[x: magic] ↦ x x",
    "X[f: magic -> t, x: magic] ↦ f (x x)",
]

[[problems.solutions]]
name = "with redundant substitution"
substitutions = [
    "Y[x: magic] ↦ x x",
    "X[f: magic -> t, x: magic] ↦ f (x x)",
    "M[x: t, y: t -> u] ↦ y x"
]
