name: free-foil-hou
version: 0.1.0.0
github: "fedor-ivn/free-foil-hou"
license: BSD-3-Clause

extra-source-files:
  - README.md
  - CHANGELOG.md
  - Syntax.cf

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/fedor-ivn/free-foil-hou#readme>

custom-setup:
  dependencies:
    base: ">= 4.11.0.0 && < 5.0"
    Cabal: ">= 2.4.0.1 && < 4.0"
    process: ">= 1.6.3.0"
    PyF:

dependencies:
  base: ">= 4.7 && < 5"
  free-foil: ">= 0.1.0"
  array: ">= 0.5.3.0"
  bifunctors:
  containers:
  kind-generics-th:
  text:
  tomland:
  doctest:

build-tools:
  alex: ">= 3.2.4"
  happy: ">= 1.19.9"
  BNFC:bnfc: ">= 2.9.4.1"

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  when:
    - condition: false
      other-modules:
        - Language.Lambda.Syntax.Test
        - Language.Lambda.Syntax.ErrM
        - Language.Lambda.Syntax.Skel

executables:
  free-foil-hou-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - free-foil-hou

tests:
  spec:
    main: Spec.hs
    source-dirs: test/hspec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - free-foil-hou
      - hspec
      - hspec-discover
      - QuickCheck

  # doctests:
  #   main: Doctests.hs
  #   source-dirs: test/doctests
  #   ghc-options:
  #     - -Wall
  #   dependencies:
  #     - free-foil-hou
  #     - doctest
