resolver: nightly-2024-10-21

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
  - git: https://github.com/fizruk/free-foil.git
    commit: b57f37331ff4817b1a29337230711e2a4914fe64
    subdirs:
      - haskell/free-foil
  - kind-generics-th-0.2.3.3@sha256:fc5f3aee46725e048a0159d73612a5d86c30017cd24ebab764347b65cffbd1d4,1519

# kind-generics-th has an outdated upper bound on template-haskell :(
allow-newer: true
allow-newer-deps:
  - kind-generics-th