-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module Language.Lambda.FCU.FCUSyntax.Abs where

newtype Id = Id String
  deriving (Eq, Ord, Show, Read)

data Term
    = WTerm Id
    | OTerm Id
    | Constructor Id
    | AppTerm Term Term
    | CompTerm Id Term
  deriving (Eq, Ord, Show, Read)

