{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for Language.
--   Generated by the BNF converter.

module Language.Lambda.FCU.FCUSyntax.Print where

import qualified Language.Lambda.FCU.FCUSyntax.Abs
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Language.Lambda.FCU.FCUSyntax.Abs.Id where
  prt _ (Language.Lambda.FCU.FCUSyntax.Abs.Id i) = doc (showString i)

instance Print Language.Lambda.FCU.FCUSyntax.Abs.MetavarId where
  prt _ (Language.Lambda.FCU.FCUSyntax.Abs.MetavarId i) = doc (showString i)

instance Print Language.Lambda.FCU.FCUSyntax.Abs.ConstructorId where
  prt _ (Language.Lambda.FCU.FCUSyntax.Abs.ConstructorId i) = doc (showString i)

instance Print Language.Lambda.FCU.FCUSyntax.Abs.Term where
  prt i e = case e of
    Language.Lambda.FCU.FCUSyntax.Abs.WTerm metavarid -> prPrec i 0 (concatD [prt 0 metavarid])
    Language.Lambda.FCU.FCUSyntax.Abs.OTerm id -> prPrec i 0 (concatD [prt 0 id])
    Language.Lambda.FCU.FCUSyntax.Abs.CTerm constructorid -> prPrec i 0 (concatD [prt 0 constructorid])
    Language.Lambda.FCU.FCUSyntax.Abs.AppTerm term1 term2 -> prPrec i 0 (concatD [prt 0 term1, doc (showString ":@"), prt 0 term2])
    Language.Lambda.FCU.FCUSyntax.Abs.AbsTerm id term -> prPrec i 0 (concatD [prt 0 id, doc (showString ":.:"), prt 0 term])

