[[problems]]
metavars = [
    "F: [t -> t] t -> t -> t",
]
constraints = [
    "∀. F[λz: t. z] = λx: t. λ y: t. y",
]

[[problems.solutions]]
name = "imitation"
metavars = []
substitutions = [
    "F[f] ↦ λx: t. λ y: t. y",
]

[[problems.solutions]]
name = "projection"
metavars = []
substitutions = [
    "F[f] ↦ λx: t. f",
]
