-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Syntax.

module AbsSyntax where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Term
    = Lam VarId Term
    | App Term Term
    | Var VarId
    | MetaVar MetaVarId
    | Cons ConsId
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype MetaVarId = MetaVarId String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype ConsId = ConsId String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype VarId = VarId String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

